#!/bin/bash

gnuplot << EOF
unset key
set term eps enhanced color solid lw 2 size 10in,7in font  'Helvetica,14'
set output '$1_curveY_$2.eps'
set title "$1-X-along-XYplane-$2"
set ylabel "amplitude"
set xlabel "x"
set palette gray
plot "$1.dat" using 1:2 with linespoints pt 6 ps 0.6 lc rgb "#000000"
EOF

epstopdf $1_curveY_$2.eps
rm $1_curveY_$2.eps
okular $1_curveY_$2.pdf &
